[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.0
    adafruit/RTClib@^2.1.4
    me-no-dev/AsyncTCP@^1.1.1
    ottowinter/ESPAsyncWebServer-esphome@^3.0.0
    bblanchon/ArduinoJson@^6.21.3